use std::path::Path;
use std::sync::Arc;

use loopal_vault_api::Vault;

use super::common::{
    DEFAULT_VAULT_NAME, discover_identity_or_exit, enumerate_vault_names, open_vault_or_exit,
    read_ssh_public_key_alongside, recipients_path_named, store_path, validate_vault_name,
    vault_dir,
};
use crate::{AgeVault, Recipients};

const GITIGNORE_CONTENT: &str =
    "# Runtime files generated by `loopal vault` operations\n*.lock\n*.tmp.*\n";

pub async fn init(cwd: &Path, name: &str) -> i32 {
    if let Err(e) = validate_vault_name(name) {
        eprintln!("{e}");
        return 1;
    }
    let dir = vault_dir(cwd, name);
    if dir.exists() {
        eprintln!("vault {name:?} already exists at {}", dir.display());
        return 1;
    }
    if let Err(e) = std::fs::create_dir_all(&dir) {
        eprintln!("failed to create {}: {e}", dir.display());
        return 1;
    }

    match try_init(cwd, name, &dir).await {
        Ok((store, rec_path)) => {
            println!("initialized {name}.vault at {}", dir.display());
            println!("recipients:  {}", rec_path.display());
            println!("store:       {}", store.display());
            0
        }
        Err(msg) => {
            eprintln!("{msg}");
            // Cleanup partial state so user can retry.
            let _ = std::fs::remove_dir_all(&dir);
            1
        }
    }
}

async fn try_init(
    cwd: &Path,
    name: &str,
    dir: &Path,
) -> Result<(std::path::PathBuf, std::path::PathBuf), String> {
    write_gitignore(dir).map_err(|e| format!("failed to write .gitignore: {e}"))?;

    let identity =
        discover_identity_or_exit().ok_or_else(|| "SSH identity discovery failed".to_string())?;
    let pubkey_line = read_ssh_public_key_alongside(&identity.path).map_err(|e| {
        format!(
            "failed to read SSH public key for {}: {e}\nexpected {}.pub alongside the private key",
            identity.path.display(),
            identity.path.display()
        )
    })?;

    let rec_path = recipients_path_named(cwd, name);
    let mut rec = Recipients::new();
    rec.add_line(&pubkey_line)
        .map_err(|e| format!("failed to parse SSH public key: {e}"))?;
    rec.write(&rec_path)
        .map_err(|e| format!("failed to write {}: {e}", rec_path.display()))?;

    let store = store_path(cwd, name);
    let vault = AgeVault::new(store.clone(), rec_path.clone(), Arc::new(identity));
    vault
        .rekey()
        .await
        .map_err(|e| format!("failed to initialize empty vault: {e}"))?;
    Ok((store, rec_path))
}

pub fn list(cwd: &Path) -> i32 {
    let names = enumerate_vault_names(cwd);
    if names.is_empty() {
        println!("(no vaults; run `loopal vaults init` to create one)");
        return 0;
    }
    for name in &names {
        let marker = if name == DEFAULT_VAULT_NAME { " *" } else { "" };
        println!("{name}{marker}");
    }
    0
}

pub async fn remove(cwd: &Path, name: &str) -> i32 {
    if let Err(e) = validate_vault_name(name) {
        eprintln!("{e}");
        return 1;
    }
    let dir = vault_dir(cwd, name);
    if !dir.exists() {
        eprintln!("no vault {name:?} at {}", dir.display());
        return 1;
    }

    let secret_names = list_secret_names(cwd, name).await;
    if !force_removal_confirmation(name, &secret_names) {
        eprintln!("aborted; vault NOT removed");
        return 1;
    }
    if let Err(e) = std::fs::remove_dir_all(&dir) {
        eprintln!("failed to remove {}: {e}", dir.display());
        return 1;
    }
    println!("removed {name}.vault");
    println!(
        "REMINDER: rotate the underlying provider values for these {} secret(s):",
        secret_names.len()
    );
    for n in &secret_names {
        println!("  - {n}");
    }
    0
}

async fn list_secret_names(cwd: &Path, name: &str) -> Vec<String> {
    match open_vault_or_exit(cwd, name) {
        Some(v) => v.list_names().await,
        None => Vec::new(),
    }
}

fn force_removal_confirmation(name: &str, secret_names: &[String]) -> bool {
    use std::io::{BufRead, Write};
    eprintln!();
    eprintln!("⚠️  Removing {name}.vault.");
    eprintln!("    All ciphertext for this vault will be deleted from disk, but anyone who has");
    eprintln!(
        "    previously decrypted these secrets — or who cloned a git history containing the"
    );
    eprintln!("    ciphertext — can still know their values. You MUST rotate the underlying");
    eprintln!("    provider-side secrets:");
    if secret_names.is_empty() {
        eprintln!("      (vault was empty — nothing to rotate)");
    } else {
        for n in secret_names {
            eprintln!("      - {n}");
        }
    }
    eprintln!();
    eprint!("Type 'rotated' to confirm you have done so: ");
    let _ = std::io::stderr().flush();
    let mut line = String::new();
    if std::io::stdin().lock().read_line(&mut line).is_err() {
        return false;
    }
    line.trim() == "rotated"
}

fn write_gitignore(dir: &Path) -> std::io::Result<()> {
    let path = dir.join(".gitignore");
    if path.exists() {
        let existing = std::fs::read_to_string(&path).unwrap_or_default();
        if existing.contains("*.lock") && existing.contains("*.tmp.*") {
            return Ok(());
        }
    }
    std::fs::write(&path, GITIGNORE_CONTENT)
}
