load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "loopal-protocol",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/loopal-message",
        "//crates/loopal-tool-invocation",
        "@crates//:chrono",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:strum",
        "@crates//:tokio",
        "@crates//:uuid",
    ],
)

rust_test(
    name = "loopal-protocol_test",
    srcs = glob(["tests/**/*.rs"]),
    compile_data = [
        "src/control.rs",
        "src/event_payload.rs",
        "src/event_summary.rs",
    ],
    crate_root = "tests/suite.rs",
    edition = "2024",
    deps = [
        ":loopal-protocol",
        "//crates/loopal-message",
        "//crates/loopal-tool-invocation",
        "@crates//:chrono",
        "@crates//:serde_json",
        "@crates//:strum",
        "@crates//:tokio",
    ],
)
