load("//build_defs/rust:platforms.bzl", "loopal_platforms")
load("//build_defs/rust:root_binary.bzl", "loopal_binary")
load("//build_defs/rust:root_tests.bzl", "loopal_root_tests")
load("//build_defs/web:npm_workspace.bzl", "desktop_npm_workspace")
load("//tools:version_env.bzl", "version_env")

desktop_npm_workspace()

loopal_platforms()

version_env(name = "version_env")

loopal_binary()

loopal_root_tests()
