load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "loopal-secret-runtime",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//crates/loopal-secret-client",
        "//crates/loopal-vault-api",
        "@crates//:aho-corasick",
        "@crates//:chrono",
        "@crates//:dirs",
        "@crates//:once_cell",
        "@crates//:regex",
        "@crates//:secrecy",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tokio",
        "@crates//:tracing",
    ],
)

rust_test(
    name = "loopal-secret-runtime-unit-test",
    crate = ":loopal-secret-runtime",
    edition = "2024",
    deps = ["@crates//:tempfile"],
)

rust_test(
    name = "loopal-secret-runtime_test",
    srcs = glob(
        ["tests/**/*.rs"],
        allow_empty = True,
    ),
    crate_root = "tests/suite.rs",
    edition = "2024",
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
    deps = [
        ":loopal-secret-runtime",
        "//crates/loopal-secret-client",
        "//crates/loopal-vault-api",
        "@crates//:secrecy",
        "@crates//:serde_json",
        "@crates//:tempfile",
        "@crates//:tokio",
    ],
)
