load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "loopal-tool-api",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    proc_macro_deps = ["@crates//:async-trait"],
    visibility = ["//visibility:public"],
    deps = [
        "//crates/loopal-error",
        "//crates/loopal-output-guard",
        "//crates/loopal-protocol",
        "//crates/loopal-secret-client",
        "//crates/loopal-tool-invocation",
        "@crates//:schemars",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:strum",
        "@crates//:thiserror",
    ],
)

rust_test(
    name = "loopal-tool-api-unit-test",
    crate = ":loopal-tool-api",
    edition = "2024",
)

rust_test(
    name = "loopal-tool-api_test",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/suite.rs",
    edition = "2024",
    proc_macro_deps = ["@crates//:async-trait"],
    deps = [
        ":loopal-tool-api",
        "//crates/loopal-backend",
        "//crates/loopal-error",
        "//crates/loopal-output-guard",
        "//crates/loopal-protocol",
        "//crates/loopal-secret-client",
        "//crates/loopal-tool-invocation",
        "@crates//:schemars",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tokio",
    ],
)
