mod runner_support;
pub use runner_support::{
    in_turn, make_cancel, make_runner, make_runner_with_channels,
    make_runner_with_question_channel, make_test_budget, make_turn_ctx,
};

mod apply_patch_compact_rehydrate_e2e_test;
mod apply_patch_partial_diff_e2e_test;
mod ask_user_schema_err_test;
mod auto_continue_edge_test;
mod auto_continue_test;
mod compact_bare_summary_e2e_test;
mod compact_force_e2e_test;
mod compact_hooks_e2e_test;
mod compact_instructions_e2e_test;
mod compact_phases_e2e_test;
mod compact_provider_error_e2e_test;
mod compact_tasks_carryover_e2e_test;
mod compact_token_sync_test;
mod compaction_run_e2e_test;
mod cron_e2e_test;
mod degeneration_e2e_test;
mod drain_pending_test;
mod e2e_event_waiters;
mod goal_e2e_test;
mod goal_kickoff_edge_test;
mod goal_kickoff_runner_test;
mod goal_kickoff_test;
mod governance_cancel_e2e_test;
mod idle_e2e_test;
mod inbox_event_test;
mod input_edge_test;
mod input_emit_fail_edge_test;
mod input_image_test;
mod input_mcp_test;
mod input_resources_test;
mod input_scheduled_test;
mod input_test;
mod integration_test;
mod interactive_cancel_test;
mod llm_test;
mod llm_truncation_test;
mod microcompact_e2e_test;
pub mod mock_provider;
mod rehydrate_e2e_test;
pub use mock_provider::make_runner_with_mock_provider;
mod cancel_finalize_e2e_test;
mod cancel_test;
mod context_budget_test;
mod continuation_bypass_test;
mod dispatch_test;
mod model_routing_test;
mod params_builder_test;
mod permission_serial_test;
mod permission_test_ext;
mod plan_approval_cancel_test;
mod plan_mode_filter_test;
mod plan_mode_test;
mod preflight_test;
mod record_message_edge_test;
mod record_message_test;
mod recovery_banner_test;
mod recovery_invariant_test;
mod resume_invariant_test;
mod resume_session_hook_test;
mod retry_cancel_test;
mod run_test;
mod stream_idle_timeout_test;
mod stream_partial_semantics_test;
mod stream_truncation_edge_test;
mod stream_truncation_test;
mod suspend_cron_e2e_test;
mod suspend_e2e_test;
mod termination_reason_test;
mod thinking_continue_test;
mod tools_edit_safety_test;
mod tools_test;
pub mod try_recover_helpers;
mod try_recover_test;
mod turn_completion_edge_test;
mod turn_completion_test;
mod turn_test;
