load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "loopal-hub-vault",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/loopal-secret-client",
        "//crates/loopal-vault-age",
        "//crates/loopal-vault-api",
        "@crates//:once_cell",
        "@crates//:regex",
        "@crates//:secrecy",
        "@crates//:tokio",
        "@crates//:tracing",
    ],
)

rust_test(
    name = "loopal-hub-vault-unit-test",
    crate = ":loopal-hub-vault",
    edition = "2024",
)

rust_test(
    name = "loopal-hub-vault_test",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/suite.rs",
    edition = "2024",
    deps = [
        ":loopal-hub-vault",
        "//crates/loopal-secret-client",
        "//crates/loopal-vault-age",
        "//crates/loopal-vault-api",
        "@crates//:secrecy",
        "@crates//:tempfile",
        "@crates//:tokio",
    ],
)
