mod decision_context;
mod degraded;
mod dispatch;
mod emitter;
pub mod permission;
pub mod permission_handler;
pub mod question;
pub mod question_handler;
pub mod traits;
pub mod unified;

pub use decision_context::DecisionContext;
pub use degraded::DegradedAction;
pub use dispatch::{into_permission_decided, into_question_decided};
pub use permission::{ClassifierPermissionHandler, DenyAllHandler, ManualPermissionHandler};
pub use permission_handler::{PermissionHandler, PermissionOutcome};
pub use question::{ClassifierQuestionHandler, ManualQuestionHandler, UnsupportedQuestionHandler};
pub use question_handler::{QuestionHandler, QuestionOutcome};
pub use traits::{AgentFrontend, EventEmitter};
pub use unified::UnifiedFrontend;
