load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "loopal-provider-api",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/loopal-error",
        "//crates/loopal-tool-api",
        "//crates/loopal-tool-invocation",
        "//crates/loopal-turn",
        "@crates//:futures",
        "@crates//:serde",
        "@crates//:serde_json",
    ],
    proc_macro_deps = ["@crates//:async-trait"],
)

rust_test(
    name = "loopal-provider-api-unit-test",
    crate = ":loopal-provider-api",
    edition = "2024",
)

rust_test(
    name = "loopal-provider-api_test",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/suite.rs",
    edition = "2024",
    deps = [
        ":loopal-provider-api",
        "//crates/loopal-provider",
        "//crates/loopal-turn",
        "@crates//:serde_json",
    ],
)
