use loopal_provider_api::{CostTier, QualityTier, SpeedTier, ThinkingCapability};

use super::catalog::ModelEntry;

pub(super) static OPENAI_MODELS: &[ModelEntry] = &[
    ModelEntry {
        id: "gpt-4o",
        provider: "openai",
        display_name: "GPT-4o",
        context_window: 128_000,
        max_output_tokens: 16_384,
        thinking: ThinkingCapability::None,
        speed: SpeedTier::Medium,
        cost: CostTier::Medium,
        quality: QualityTier::Standard,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
    ModelEntry {
        id: "gpt-4o-mini",
        provider: "openai",
        display_name: "GPT-4o Mini",
        context_window: 128_000,
        max_output_tokens: 16_384,
        thinking: ThinkingCapability::None,
        speed: SpeedTier::Fast,
        cost: CostTier::Low,
        quality: QualityTier::Basic,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
    ModelEntry {
        id: "gpt-4.1",
        provider: "openai",
        display_name: "GPT-4.1",
        context_window: 1_047_576,
        max_output_tokens: 32_768,
        thinking: ThinkingCapability::None,
        speed: SpeedTier::Medium,
        cost: CostTier::Medium,
        quality: QualityTier::Standard,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
    ModelEntry {
        id: "gpt-4.1-mini",
        provider: "openai",
        display_name: "GPT-4.1 Mini",
        context_window: 1_047_576,
        max_output_tokens: 32_768,
        thinking: ThinkingCapability::None,
        speed: SpeedTier::Fast,
        cost: CostTier::Low,
        quality: QualityTier::Basic,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
    ModelEntry {
        id: "gpt-4.1-nano",
        provider: "openai",
        display_name: "GPT-4.1 Nano",
        context_window: 1_047_576,
        max_output_tokens: 32_768,
        thinking: ThinkingCapability::None,
        speed: SpeedTier::Fast,
        cost: CostTier::Low,
        quality: QualityTier::Basic,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
    ModelEntry {
        id: "o3",
        provider: "openai",
        display_name: "o3",
        context_window: 200_000,
        max_output_tokens: 100_000,
        thinking: ThinkingCapability::ReasoningEffort,
        speed: SpeedTier::Slow,
        cost: CostTier::High,
        quality: QualityTier::Premium,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
    ModelEntry {
        id: "o3-mini",
        provider: "openai",
        display_name: "o3-mini",
        context_window: 200_000,
        max_output_tokens: 100_000,
        thinking: ThinkingCapability::ReasoningEffort,
        speed: SpeedTier::Medium,
        cost: CostTier::Medium,
        quality: QualityTier::Standard,
        supports_tools: true,
        supports_vision: false,
        supports_prefill: true,
    },
    ModelEntry {
        id: "o4-mini",
        provider: "openai",
        display_name: "o4-mini",
        context_window: 200_000,
        max_output_tokens: 100_000,
        thinking: ThinkingCapability::ReasoningEffort,
        speed: SpeedTier::Medium,
        cost: CostTier::Medium,
        quality: QualityTier::Standard,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
    ModelEntry {
        id: "gpt-5.5",
        provider: "openai",
        display_name: "GPT-5.5",
        context_window: 1_000_000,
        max_output_tokens: 128_000,
        thinking: ThinkingCapability::None,
        speed: SpeedTier::Medium,
        cost: CostTier::High,
        quality: QualityTier::Premium,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
];
