use loopal_provider_api::{CostTier, QualityTier, SpeedTier, ThinkingCapability};

use super::catalog::ModelEntry;

// supports_prefill: false for all Anthropic models with built-in thinking
// (BudgetRequired/Adaptive) — these reject assistant-prefill at API level
// regardless of `thinking` request field.
pub(super) static ANTHROPIC_MODELS: &[ModelEntry] = &[
    ModelEntry {
        id: "claude-sonnet-4-20250514",
        provider: "anthropic",
        display_name: "Claude Sonnet 4",
        context_window: 200_000,
        max_output_tokens: 64_000,
        thinking: ThinkingCapability::BudgetRequired,
        speed: SpeedTier::Medium,
        cost: CostTier::Medium,
        quality: QualityTier::Standard,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: false,
    },
    ModelEntry {
        id: "claude-sonnet-4-6",
        provider: "anthropic",
        display_name: "Claude Sonnet 4.6",
        context_window: 1_000_000,
        max_output_tokens: 64_000,
        thinking: ThinkingCapability::Adaptive,
        speed: SpeedTier::Medium,
        cost: CostTier::Medium,
        quality: QualityTier::Standard,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: false,
    },
    ModelEntry {
        id: "claude-opus-4-20250514",
        provider: "anthropic",
        display_name: "Claude Opus 4",
        context_window: 200_000,
        max_output_tokens: 32_000,
        thinking: ThinkingCapability::BudgetRequired,
        speed: SpeedTier::Slow,
        cost: CostTier::High,
        quality: QualityTier::Premium,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: false,
    },
    ModelEntry {
        id: "claude-opus-4-6",
        provider: "anthropic",
        display_name: "Claude Opus 4.6",
        context_window: 1_000_000,
        max_output_tokens: 128_000,
        thinking: ThinkingCapability::Adaptive,
        speed: SpeedTier::Slow,
        cost: CostTier::High,
        quality: QualityTier::Premium,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: false,
    },
    ModelEntry {
        id: "claude-opus-4-7",
        provider: "anthropic",
        display_name: "Claude Opus 4.7",
        context_window: 1_000_000,
        max_output_tokens: 128_000,
        thinking: ThinkingCapability::Adaptive,
        speed: SpeedTier::Slow,
        cost: CostTier::High,
        quality: QualityTier::Premium,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: false,
    },
    ModelEntry {
        id: "claude-haiku-3-5-20241022",
        provider: "anthropic",
        display_name: "Claude 3.5 Haiku",
        context_window: 200_000,
        max_output_tokens: 8_192,
        thinking: ThinkingCapability::None,
        speed: SpeedTier::Fast,
        cost: CostTier::Low,
        quality: QualityTier::Basic,
        supports_tools: true,
        supports_vision: true,
        supports_prefill: true,
    },
];
