load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "loopal-secret-client",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//crates/loopal-ipc",
        "//crates/loopal-output-guard",
        "//crates/loopal-protocol",
        "@crates//:once_cell",
        "@crates//:regex",
        "@crates//:secrecy",
        "@crates//:serde_json",
        "@crates//:thiserror",
        "@crates//:tokio",
    ],
)

rust_test(
    name = "loopal-secret-client-unit-test",
    crate = ":loopal-secret-client",
    edition = "2024",
)
