//! Hub-facing methods: register, route, spawn, lifecycle queries,
//! topology, shutdown, permission/question relay, control/interrupt.

use super::super::Method;

/// Register with Hub after connecting.
pub const HUB_REGISTER: Method = Method {
    name: "hub/register",
};

/// Route a point-to-point message to another agent.
pub const HUB_ROUTE: Method = Method { name: "hub/route" };

/// Spawn a new agent process. In-hub semantics: caller may pass `cwd`
/// and `fork_context`; child inherits the caller's filesystem view.
pub const HUB_SPAWN_AGENT: Method = Method {
    name: "hub/spawn_agent",
};

/// Spawn a new agent on this Hub on behalf of a remote (cross-hub) caller.
/// Forwarded by MetaHub. Receiving Hub MUST use its own `default_cwd`;
/// `cwd` / `fork_context` / `resume` fields are rejected by the handler
/// because the caller's filesystem view is not shared.
pub const HUB_SPAWN_REMOTE_AGENT: Method = Method {
    name: "hub/spawn_remote_agent",
};

/// Wait for a spawned agent to finish and return its output.
pub const HUB_WAIT_AGENT: Method = Method {
    name: "hub/wait_agent",
};

/// List all connected agents.
pub const HUB_LIST_AGENTS: Method = Method {
    name: "hub/list_agents",
};

/// Query a single agent's info (lifecycle, parent, children, output).
pub const HUB_AGENT_INFO: Method = Method {
    name: "hub/agent_info",
};

/// Get the full agent topology tree.
pub const HUB_TOPOLOGY: Method = Method {
    name: "hub/topology",
};

/// Shut down a specific agent.
pub const HUB_SHUTDOWN_AGENT: Method = Method {
    name: "hub/shutdown_agent",
};

/// Shut down the entire Hub process. Triggers `Hub.shutdown_signal`,
/// causing the standalone `--hub-only` process to drop all agents,
/// close the listener, and exit. UI clients receive a TCP disconnect.
pub const HUB_SHUTDOWN: Method = Method {
    name: "hub/shutdown",
};

/// UI → Hub: respond to a `ToolPermissionRequest` event.
///
/// Params: `{ agent_name: String, tool_call_id: String, allow: bool }`.
/// Hub looks up `Hub.pending_permissions[(agent_name, tool_call_id)]`,
/// forwards `{allow}` to the suspended agent IPC request, and emits
/// `ToolPermissionResolved` so other UIs clear their dialogs.
/// `agent_name` is required: same `tool_call_id` may be in flight on
/// multiple agents simultaneously and must be disambiguated.
pub const HUB_PERMISSION_RESPONSE: Method = Method {
    name: "hub/permission_response",
};

/// UI → Hub: respond to a `UserQuestionRequest` event.
///
/// Params: `{ agent_name: String, question_id: String, answers: Vec<String> }`.
/// `question_id` is generated by Hub (UUID), but `agent_name` is still
/// part of the key for symmetry with permission and to scope cleanup.
pub const HUB_QUESTION_RESPONSE: Method = Method {
    name: "hub/question_response",
};

/// Route a control command to a named agent.
pub const HUB_CONTROL: Method = Method {
    name: "hub/control",
};

/// Route an interrupt signal to a named agent.
pub const HUB_INTERRUPT: Method = Method {
    name: "hub/interrupt",
};

/// Query Hub status (uplink, agent count, etc).
pub const HUB_STATUS: Method = Method { name: "hub/status" };
