load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "loopal-config",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/loopal-decision-api",
        "//crates/loopal-error",
        "//crates/loopal-protocol",
        "//crates/loopal-provider-api",
        "//crates/loopal-secret-runtime",
        "//crates/loopal-tool-api",
        "//crates/loopal-vault-age",
        "//crates/loopal-vault-api",
        "@crates//:dirs",
        "@crates//:indexmap",
        "@crates//:libc",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sha2",
        "@crates//:thiserror",
        "@crates//:tracing",
    ],
)

rust_test(
    name = "loopal-config-unit-test",
    crate = ":loopal-config",
    edition = "2024",
    proc_macro_deps = ["@crates//:async-trait"],
    deps = [
        "@crates//:filetime",
        "@crates//:tempfile",
    ],
)

rust_test(
    name = "loopal-config_test",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/suite.rs",
    edition = "2024",
    deps = [
        ":loopal-config",
        "//crates/loopal-decision-api",
        "//crates/loopal-provider-api",
        "//crates/loopal-tool-api",
        "@crates//:filetime",
        "@crates//:serde_json",
        "@crates//:tempfile",
    ],
)
