"""Root Loopal binary target."""

load("@rules_rust//rust:defs.bzl", "rust_binary")

def loopal_binary():
    rust_binary(
        name = "loopal",
        srcs = native.glob(["src/**/*.rs"]),
        edition = "2024",
        rustc_env_files = [":version_env"],
        stamp = 1,
        visibility = ["//visibility:public"],
        deps = [
            "//crates/loopal-acp",
            "//crates/loopal-agent-client",
            "//crates/loopal-agent-hub",
            "//crates/loopal-agent-server",
            "//crates/loopal-backend",
            "//crates/loopal-config",
            "//crates/loopal-context",
            "//crates/loopal-decision-api",
            "//crates/loopal-git",
            "//crates/loopal-hub-vault",
            "//crates/loopal-ipc",
            "//crates/loopal-meta-hub",
            "//crates/loopal-protocol",
            "//crates/loopal-provider-api",
            "//crates/loopal-runtime",
            "//crates/loopal-secret-runtime",
            "//crates/loopal-session",
            "//crates/loopal-storage",
            "//crates/loopal-telemetry",
            "//crates/loopal-tool-api",
            "//crates/loopal-tui",
            "//crates/loopal-vault-age",
            "//crates/loopal-vault-api",
            "//crates/loopal-view-state",
            "//crates/loopal-workspace",
            "//crates/tools/process/background:loopal-tool-background",
            "@crates//:anyhow",
            "@crates//:chrono",
            "@crates//:clap",
            "@crates//:dirs",
            "@crates//:secrecy",
            "@crates//:serde",
            "@crates//:serde_json",
            "@crates//:tokio",
            "@crates//:tracing",
            "@crates//:tracing-appender",
            "@crates//:tracing-subscriber",
            "@crates//:uuid",
        ],
    )
